package com.chhaya.blog.models;

import java.util.ArrayList;
import java.util.List;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Entity
@Table(name="users")//here we changing table name as users
//here we using "lombok" for generte constructor,getter and setters.
@NoArgsConstructor
@Getter
@Setter
public class User
{
	
	@Id//id set as primary key.
    @GeneratedValue(strategy=GenerationType.AUTO)//id will be autogenerated.
     private int id;
    
    @Column(name="user_name",nullable=false,length=100)//nullable=false  null value not allowed.lenghth of name is 100.
     private String name;
     private String email;
     private String password;
     private String about;
	
	
   //here making the one to many relationship between user and post(one user has multiple post)
 	@OneToMany(mappedBy = "user",cascade=CascadeType.ALL,fetch=FetchType.LAZY)
 	//mappedBy = "user"  ->In post table on which column we have to mapped."user" is column in post tabel.
 	//fetch=FetchType.LAZY  means parent delet kiya to child delet nhi hoga.
 	//cascade=CascadeType.ALL means when we delet parent then automaticall child will delet.and when we add parent then child will automatially get saved.
 	private List<Post> posts=new ArrayList<>();
 	 
         
         
         
         
}
